### ISSUE TITLE
Spawning a child actor

### ISSUE THREAD

**Issue by dispalt** [nokia/akka-typed-persistence#5]
Is there an example spawning a child actor somewhere?  I seem to be running into trouble with it, I am using the `ctx.ctx.spawn` facility:

```
[ERROR] [12/20/2016 14:32:09.070] [pingSystem-akka.actor.default-dispatcher-4] [akka://pingSystem/user/pingActor/$a] Wrap.message called with CheckZipStart(SessionId(272c5c45-9269-434c-a94c-893bc91bb815),94110,1482273129041,Actor[akka://pingSystem/system/testActor-1#496883580]); maybe the persistent typed behavior was deployed as a regular actor?
java.lang.IllegalStateException: Wrap.message called with CheckZipStart(SessionId(272c5c45-9269-434c-a94c-893bc91bb815),94110,1482273129041,Actor[akka://pingSystem/system/testActor-1#496883580]); maybe the persistent typed behavior was deployed as a regular actor?
	at com.nokia.ntp.ct.persistence.package$.impossible(package.scala:96)
	at com.nokia.ntp.ct.persistence.PersistentBehavior$Wrap.message(persistentBehavior.scala:110)
	at akka.typed.adapter.ActorAdapter$$anonfun$receive$1.applyOrElse(ActorAdapter.scala:32)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.typed.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:9)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by dispalt** [comment]
I got it work using `deployInto` which judging by the comments is necessary since it utilizes the bridge between untyped and typed.

My issue is the failure domain side, not a huge issue, but was curious since spawned actors are no longer easy to hang off other actors so you have to change your failure handling code.

**Comment by dilation** [comment]
Yes, unfortunately if an actor is persistent, currently it's necessary to use our custom `deployInto`. Although you're right that we should be able to create child actors. I'll have to think about that, but I think it's possible to write another `deployInto`, which creates a child actor...
